### ISSUE TITLE
System.ArgumentException

### ISSUE THREAD

**Issue by Blueduckraider50** [drjaydenm/SharpText#11]
System.ArgumentException: 'An item with the same key has already been added.'

I got the "Font font = new Font("Fonts/OpenSans-Regular.woff", 13);"
and it's throwing that error.

And no matter what I do with it, it always throws an error

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SharpText.Core;

namespace TextGame
{
	class Program
	{
		static void Main(string[] args)
		{
			Font font = new Font("Fonts/OpenSans-Regular.woff", 13);

		}
	}
}
```

**Comment by drjaydenm** [comment]
Did you manage to resolve this issue? I haven't been able to reproduce it, and the demo app uses Open Sans directly with size 13 font and it works correctly. I'd be happy to take a look if you had an app which reproduces the issue

**Comment by Blueduckraider50** [comment]
It's ages ago since I tried it, don't think I even have the project anymore, (Gave up on it when I  couldn't get it to work after testing & testing & testing).
Started a new project today, following the DemoApp, not had any issues so far.

**Comment by drjaydenm** [comment]
That sounds great then 🙂 Feel free to load another issue if you encounter any other problem
