### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by Perksey** [drjaydenm/SharpText#9]
This project is currently licensed under LGPL. This is fine for most cases, however it prevents static linking which is an integral part of Xamarin.iOS and Monodroid. Is there any way to get the license relaxed a bit to allow usage of the library in more places?

**Comment by drjaydenm** [comment]
Yeah that is a great point, and is an oversight of mine. I've updated it to the MIT license which is much more flexible. Does that help you?

**Comment by Perksey** [comment]
Yes that's brilliant, thank you!
